// <auto-generated />
using System;
using CTIN.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTIN.DataAccess.Migrations
{
    [DbContext(typeof(NATemplateContext))]
    [Migration("20200518160931_them_feedback")]
    partial class them_feedback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CTIN.DataAccess.Contexts.Files", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("data")
                        .HasColumnName("data");

                    b.Property<string>("dataDb")
                        .HasColumnName("dataDb");

                    b.Property<byte[]>("source")
                        .HasColumnName("source");

                    b.HasKey("id");

                    b.ToTable("Files","stm");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.Acttachments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataDb")
                        .HasColumnName("dataDb");

                    b.Property<string>("fileData")
                        .HasColumnName("FileData");

                    b.HasKey("id");

                    b.ToTable("Acttachments","pm");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("address");

                    b.Property<string>("avatar");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.Categoryfilm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataDb")
                        .HasColumnName("dataDb")
                        .IsUnicode(false);

                    b.Property<string>("discription")
                        .HasColumnName("discription");

                    b.Property<int>("level")
                        .HasColumnName("level");

                    b.Property<string>("linkImg")
                        .HasColumnName("linkImg");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<byte>("pointword")
                        .HasColumnName("pointword");

                    b.Property<int>("totalUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("totalUser")
                        .HasDefaultValue(0);

                    b.Property<int>("totalWord")
                        .HasColumnName("totalWord");

                    b.HasKey("id");

                    b.ToTable("categoryfilm");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.Rank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataDb")
                        .HasColumnName("dataDb")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("name")
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<int>("pointStage")
                        .HasColumnName("pointStage");

                    b.Property<int>("pointmaxStage");

                    b.Property<int>("star");

                    b.HasKey("id");

                    b.ToTable("rank");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.Tips", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasMaxLength(100);

                    b.Property<string>("dataDb")
                        .HasColumnName("dataDb")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("id");

                    b.ToTable("tips");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.UserLeanning", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("filmFinish")
                        .HasColumnName("filmfinish");

                    b.Property<string>("filmFinishForget")
                        .HasColumnName("filmfinishforget");

                    b.Property<string>("filmForgeted")
                        .HasColumnName("filmforgeted");

                    b.Property<string>("filmLearnning")
                        .HasColumnName("filmlearnning");

                    b.Property<string>("filmPunishing")
                        .HasColumnName("filmpunishing");

                    b.Property<string>("listFilmLearned")
                        .HasColumnName("listfilmlearned");

                    b.Property<int>("point")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("point")
                        .HasDefaultValue(0);

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("userLeanning");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.WordFilm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("answerWrongEn")
                        .HasColumnName("answerWrongEn");

                    b.Property<string>("answerWrongVn")
                        .HasColumnName("answerWrongVn");

                    b.Property<int>("categoryfilmid");

                    b.Property<string>("dataDb")
                        .HasColumnName("dataDb")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("feedBackaboutWord")
                        .HasColumnName("feedBackaboutWord");

                    b.Property<string>("fullName")
                        .HasColumnName("fullname")
                        .HasMaxLength(500);

                    b.Property<string>("listPeopleContribute")
                        .HasColumnName("listPeopleContribute");

                    b.Property<long?>("size");

                    b.Property<int>("stt");

                    b.Property<string>("textEn")
                        .HasColumnName("textEn")
                        .HasMaxLength(500);

                    b.Property<string>("textVn")
                        .HasColumnName("textVn")
                        .HasMaxLength(500);

                    b.Property<string>("urlaudio")
                        .HasColumnName("urlaudio")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("id");

                    b.HasIndex("categoryfilmid");

                    b.ToTable("WordFilm");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.UserLeanning", b =>
                {
                    b.HasOne("CTIN.DataAccess.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("CTIN.DataAccess.Models.WordFilm", b =>
                {
                    b.HasOne("CTIN.DataAccess.Models.Categoryfilm", "categoryfilm")
                        .WithMany()
                        .HasForeignKey("categoryfilmid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CTIN.DataAccess.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CTIN.DataAccess.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CTIN.DataAccess.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CTIN.DataAccess.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
